version: "3.7"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tototo
  envoy:
    image: envoyproxy/envoy
    network_mode: host
    volumes:
      - type: bind
        read_only: true
        source: ./envoy/envoy.yaml
        target: /etc/envoy/envoy.yaml
