version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tototo
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        read_only: true
        source: ./mariadb/
        target: /docker-entrypoint-initdb.d/
  envoy:
    image: envoyproxy/envoy
    network_mode: host
    volumes:
      - type: bind
        read_only: true
        source: ./envoy/envoy.yaml
        target: /etc/envoy/envoy.yaml
